### ISSUE TITLE
Support macOS CLIs with Xcode 10.2

### ISSUE THREAD

**Issue by keith** [bazelbuild/rules_swift#162]
As of Xcode 10.2 beta 4, the `swift_static` directory inside Xcode has disappeared. When you attempt to use `--static-swift-stdlib` with Swift Package Manager this seems to be a very intentional change:

```
% swift build --static-swift-stdlib
warning: Swift compiler no longer supports statically linking the Swift libraries. They're included in the OS by default starting with macOS Mojave 10.14.4 beta 3. For macOS Mojave 10.14.3 and earlier, there's an optional Swift library package that can be downloaded from "More Downloads" for Apple Developers at https://developer.apple.com/download/more/
```

In order to continue supporting older OS versions with CLIs, we'll need to add the `rpath` to the Swift libraries inside Xcode (or the system location for 10.14.4 and up). This change will also affect rules_apple which uses the static functionality for macOS CLIs and dylibs.

**Comment by allevato** [comment]
Fixed by #163 (ac13c886e75db56ddde9200338e374e2818bfe1b).

There's a tiny workaround in there for older OSes that points the rpath to the Swift library directory inside Xcode so that local builds (like host tools written in Swift) still run without needing the [extra package from Apple](https://download.developer.apple.com/Developer_Tools/Swift_5_Runtime_Support_for_Command_Line_Tools_Xcode_10.2_beta_4/Swift_5_Runtime_Support_for_Command_Line_Tools_Xcode_10.2_beta_4.dmg) installed, but I'll remove that eventually.
