### ISSUE TITLE
Propagate Transitive Swift Sources in ObjcProvider

### ISSUE THREAD

**Issue by burakcoskun** [bazelbuild/rules_swift#229]
ObjcProvider has a source field that propagates transitive source files.
Here: https://docs.bazel.build/versions/master/skylark/lib/ObjcProvider.html#source

In swift_library it is not set and I couldn't find transitive source files anywhere else either. Having transitive source files is a bit counterintuitive but we need it at our codegen script happens in swift_binary. 

So what do you think of setting ObjcProvider.source field for swift_library as well? It should be a small change.

If this doesn't suite the project, I think we can also find easy workarounds without updating rules_swift.

**Comment by allevato** [comment]
Reusing `ObjcProvider.source` for this seems like the wrong thing to do, since Swift files aren't Objective-C sources. If Bazel ever wanted to do something else with that provider field, assuming that the files are Objective-C, we'd break that.

Even if we wanted to add transitive sources to `SwiftInfo`, that's a lot of information to pass around that would not actually be used by the rules themselves, and that adds to the memory footprint of every build.

My recommendation here would be to write your own custom rule to handle your codegen. Have that rule attach an aspect to its deps, and your aspect's implementation can inspect the `srcs` attribute of `swift_library` targets directly, and then propagate the necessary information up the chain through a provider that you define yourself. (And also propagate the underlying `SwiftInfo` providers so that you can use your own rule as a dependency of other `swift_{binary,library}` targets.)

This gives you the ability to collect the information that you need without imposing it on every `swift_library` in use.

**Comment by burakcoskun** [comment]
Yep I agree better not to add that to `swift_library`. 

I am not familiar with bazel much but your recommendation seems reasonable. Custom codegen rule will attach aspects to `swift_library` rules, that will kind of sideload information we want and will have access to `swift_library` attributes, seems nice.

Thanks,
Closing the issue

**Comment by burakcoskun** [comment]
that worked. i used aspects and that came in handy.
only difference is i haven't(at least not explicitly) provided `SwiftInfo` in the new codegen rule but I can still make it a dependency to other `swift_library` targets.
