### ISSUE TITLE
Add regular swift_library options to swift_proto_library

### ISSUE THREAD

**Issue by steeve** [bazelbuild/rules_swift#29]
For instance, `swift_proto_library` does not allow to define its own `module_name` or `copts`.

**Comment by allevato** [comment]
This is not possible with the current aspect-based design, unfortunately.

`swift_proto_library` doesn't register any actions of its own; it merely acts as the point in the dependency graph where the proto generation aspect is attached to the descendent `proto_library` targets. As such, the compilation actions are attached to the `proto_library` targets themselves, and there's no way for it to read attributes from the `swift_proto_library` target that kicked off that evaluation.

More information about the motivation behind this design for protos in general can be found [here](https://blog.bazel.build/2017/02/27/protocol-buffers.html). It's unlikely that we'll revisit this, because the ability to have any reference to a proto library resolve to the same node is very important to prevent duplication and avoid collisions, especially when dealing with large graphs of dependencies where you may not always be aware of what's getting pulled in if a dependency changes underneath you.

**Comment by steeve** [comment]
Thanks, just saw the reply. Would the `module_name` be possible though ?

**Comment by allevato** [comment]
Sadly no—the reason is because even if you declared a `swift_proto_library` for each `proto_library` target, the code generation and compilation occurs in an aspect attached to the `proto_library`. (The `swift_proto_library` really just handles propagation of build artifacts.) There's no way for the aspect to access attributes from a `swift_proto_library` because it could be applied from _any_ `swift_proto_library` target, so the results need to be consistent each time.

For example, if you have `swift_proto_library` "A" that depends on `proto_library` "P", and then a different `swift_proto_library` "B" that depends on `proto_library` "Q" which depends on `proto_library` "P", then we need to produce the same code for "P" regardless of whether you include "A", "B", or both in your dependency tree. (This is also why `swift_proto_library` targets don't depend on each other; it's just a "bridge" between a `swift_library` and the protos.)

I sympathize with dissatisfaction over the ugly module names, but in the monorepo case, it's really the only way to ensure a low probability of collisions. (And it _does_ have the benefit of making the module discoverable if you already know the target's label.) Even if we wanted to lift this restriction and make it configurable, the aspect-based design doesn't provide a way to achieve that cleanly.

**Comment by steeve** [comment]
Hey @allevato, so I've done some experiments this weekend and here's what I come up with.

Basically, since we are exporting the models inside a `.framework`, having one swift module per proto file is not an option for us. But I think I've come up with a solution that works and doesn't break existing code in `rules_swift`.

What I did is as follow:
- expose the generated `.pb.swift` as an output group of the `swift_proto_library`
- switch to `FileNaming=PathToUnderscores` so that file names don't collide
- disables modules usage when generating the `.pb.swift` files by adding a `modules` attr (default `on`) to disable the proto module mapping file generation
- use the file from the output group in a `swift_library` with a regular module name

**Comment by steeve** [comment]
I've put the draft implementation at https://github.com/znly/rules_swift/tree/steeve/protomodules

**Comment by allevato** [comment]
> Basically, since we are exporting the models inside a .framework, having one swift module per proto file is not an option for us.

It's one module per `proto_library`, not one module per `.proto` file (unless your `proto_library` targets are structured that way, but more to the point, can you elaborate on why multiple modules not work for you in the framework case? Can the Modules directory of a .framework bundle not contain multiple .swiftmodules? (I've never tried this, but a restriction like that would surprise me since a framework is really just another kind of search path.)

Is the issue merely that having the protos in multiple modules feels "ugly" to the end user, who has to import something other than just `FrameworkName` to get the types they want? If that's the case, you can work around that using the `@_exported` attribute. In your main framework module, you can have a file named, say, `exports.swift` (the name doesn't actually matter) and write something like this:

```swift
@_exported import my_ugly_proto_module_name
@_exported import some_other_ugly_proto_module_name
@_exported import yet_another_ugly_proto_module_name
```

Then, when someone imports your framework's module, they get those imports for free (and the symbol names are shadowed in the new module).

One of these would be preferable to adding more switches that can be flipped to the rules, because things can get ugly if someone starts depending on the same protos in multiple ways (i.e., from multiple modules), and even though the current state of things isn't ideal, it's at least _safe_.

**Comment by steeve** [comment]
Thanks for the great reply @allevato 

Let me explain my use case first perhaps: my final target is a `ios_static_framework` that we distribute to the iOS team. The issue with `@_exported` is that even though the export works, ultimately Xcode complains that the original `my_ugly_proto_module_name` module is missing.

What I'm doing right now is this, to make sure the generated framework is self contained:
```python
native.filegroup(
    name = "myprotos",
    srcs = [
        "//:my_ugly_proto_module_name",
    ],
    output_group = "pbswift_files",
)

swift_library(
    name = "CleanModels",
    srcs = [
        ":myprotos",
    ],
    module_name = "CleanModels",
    visibility = ["//visibility:public"],
)
```

Although it works well, it's not so good as it creates one compilation action with all the protos.

If there is a way to make `swift_module_alias` work with a Swift `ios_statis_framework`, for sure I'll take it!

**Comment by allevato** [comment]
I dug into the Swift sources and it looks like the framework name and the module name must match after all ☹️

Relevant logic is around here, where `moduleFramework` and `moduleFilename` are derived from the same module identifier: https://github.com/apple/swift/blob/master/lib/Serialization/SerializedModuleLoader.cpp#L244

In retrospect, that makes sense—it doesn't want to search _every_ `.framework` bundle in the framework search directories to find the module, it just wants to check to see if a particular framework is there.

I don't have a great answer for this at this time, but it's not a protobuf-specific problem. This would be a problem for anyone who would want to put multiple `swift_library` targets into a framework as well.

**Comment by steeve** [comment]
For now, I guess I'll still rely on our `modules: "off"` attr on `swift_proto_library` + `pbswift_files` output group. It works nice for us (but it does compile all the protobuf files in one shot).

I can open a PR (perhaps not to be merged) in the interim once I've rebased it.
