### ISSUE TITLE
linkopts are backwards

### ISSUE THREAD

**Issue by mpalczew** [bazelbuild/rules_swift#338]
adding link opts to a `swift_library` doesn't work as expected. 

*Expected*
```
linkopts = ["-weak_framework Combine"]
```
This fails because it treats this as one flag.  There is no option '-weak_framework Combine'
```
linkopts = ["-weak_framework", "Combine"]
```
This also fails because the options are passed in as 'Combine' '-weak_framework' 
*Workaround*
```
linkopts = ["Combine", "-weak_framework"]
```

**Comment by allevato** [comment]
More information is needed. What rule is doing the linking in this case, a `swift_binary` or something from rules_apple like `ios_application`?

If it's the latter, we have to use `ObjcProvider` to propagate linker flags, which is known to be buggy because it improperly deduplicates flags under certain circumstances, and I wonder if that's what's happening here. Are you using `-weak_framework` anywhere else in your build graph?

(Your expected case is wrong though—a single string should be expected to be treated as a single flag without additional processing, otherwise flags with spaces in them wouldn't be possible.)

**Comment by mpalczew** [comment]
Fair enough on the expected case. I'm using the link opts in my swift_library. My ios_ui_test won't link without this change.

**Comment by allevato** [comment]
Can you provide some more information? Do you have any other `swift_libraries` or `objc_libraries` in the dependency graph that also provide custom `linkopts` (especially `-weak_framework`)? Can you provide a more complete snapshot of your targets, or a small/redacted repro case?

**Comment by mpalczew** [comment]
I can probably throw something together, will take a little time. 
I'm basically doing something like. 

swift_lib  A
swift_lib A_test_lib   dep -> A
ios_ui_test A_test dep -> A_test_lib

**Comment by brentleyjones** [comment]
I just ran into this as well. We needed to reverse the ordering to get weak linking working.

**Comment by keith** [comment]
This is the entire config you need to repro this issue:

```
load("@build_bazel_rules_apple//apple:ios.bzl", "ios_unit_test")
load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")

swift_library(
    name = "foo",
    srcs = ["foo.swift"],
    linkopts = [
        "-weak_framework",
        "CoreNFC",
    ],
)

ios_unit_test(
    name = "test",
    deps = ["foo"],
    minimum_os_version = "11.0",
)
```

**Comment by keith** [comment]
Here's a fix https://github.com/bazelbuild/rules_swift/pull/383

**Comment by keith** [comment]
Another issue came up on that PR, but in the meantime you can workaround this bug with:

```
    linkopts = [
        "-Wl,-weak_framework,Bar",
        "-Wl,-weak_framework,Foo",
    ],
```

and these will work since clang will pass them through to ld with no problem
