### ISSUE TITLE
Support static frameworks with swift_import

### ISSUE THREAD

**Issue by keith** [bazelbuild/rules_swift#36]
Currently [`swift_import`](https://github.com/bazelbuild/rules_swift/blob/master/doc/rules.md#swift_import) supports vendoring static `.a` files to be imported by other modules. We currently vendor our 3rd party dependencies in static frameworks, which are created with this layout:

```
Foo.framework
├── Foo
├── Foo.bundle
│   └── Images.xcassets
└── Modules
    └── Foo.swiftmodule
        ├── arm.swiftdoc
        ├── arm.swiftmodule
        ├── arm64.swiftdoc
        ├── arm64.swiftmodule
        ├── i386.swiftdoc
        ├── i386.swiftmodule
        ├── x86_64.swiftdoc
        └── x86_64.swiftmodule
```

This allows us to move around this single directory, which encapsulates all requirements to include this library.

The [`objc_import`](https://docs.bazel.build/versions/master/be/objective-c.html#objc_import) rule includes the resources part of this, but also not the framework binary part.

Currently if you try and reference this binary, you receive this error:

```
ERROR: /path:10:14: in archives attribute of swift_import rule //Foo:Foo: source file '//Foo:Foo' is misplaced here (expected a)
```

Would it be reasonable to support resources and framework binaries with `swift_import`? Otherwise is there a better way to include this library layout?

**Comment by allevato** [comment]
Extending `swift_import` to support framework-style bundles should be possible from a linking point of view.

To handle resources, we could certainly add `bundles`/`resources`/`structured_resources` to `swift_import` as well (in fact, we still don't have `bundles` on `swift_library` yet, either). There's a bit of a "race condition" here because we're also in the process of migrating the logic over at [rules_apple](https://github.com/bazelbuild/rules_apple) to use `data` attribute instead and eventually drop all of the Apple-resource-specific attributes from `objc_library`, so *adding* those attributes to `swift_import` only to remove them later is a bit weird, but we can weigh all of these options.

**Comment by keith** [comment]
Thanks for the quick answer. On the resources side, is there context somewhere I can read about how `data` will replace these other attributes?

**Comment by allevato** [comment]
We don't have any design docs on it yet; we're working on the proof of concept before we try to lock too many of the details down. Once we have a migration guide of sorts, I imagine we can post something in rules_apple.

**Comment by keith** [comment]
We're currently symlinking the framework binary as a static library to satisfy the naming requirement, and we're passing the directory of swiftmodules. Which works because rules_swift only uses that to derive a -I flag


--
Keith Smiley

**Comment by allevato** [comment]
Thinking about this some more, this use case should be dealt with by the new [`apple_framework_import`](https://github.com/bazelbuild/rules_apple/blob/master/apple/internal/apple_framework_import.bzl) in rules_apple.

There's still some work we need to do in the Swift rules to bind these together. In particular, we pass framework search paths (`-F`) from the framework fields of `ObjcProvider` already, but I believe we need to add the actual `-framework` flags to make compilation work for the `swiftc` invocation. That code is in [`objc_compile_requirements`](https://github.com/bazelbuild/rules_swift/blob/master/swift/internal/compiling.bzl#L289).

I _think_ this should work; for compilation actions, `-framework` should still handle the search paths correctly. And I believe the code already in that function should be able to suppress any autolinking behavior that the compiler might try to add if it assumes that it's a dynamic framework. I haven't tested this, though.

But if this works, it would be a much better approach than extending `swift_import`, because it means we don't have to handle the multiple-architecture case or the resources case—those are specifically Apple platform issues that are best handled in rules_apple.

**Comment by keith** [comment]
This should definitely work. With our current non-Bazel setup we do the same thing, pass the -F and the -framework and that's all. We'll just have to make sure when passing the -framework that we no longer pass the framework binary directly to ld as we do now.


--
Keith Smiley

**Comment by codesuki** [comment]
Thanks! I was thinking of renaming the binary appending `.a`. Good to know it's supposed to work. 
The `.a` file I set in `archives` and the top folder containing the different `arch.swiftmodule`s (`Foo.framework/Modules/Foo.swiftmodule` from your example) I set in `swiftmodules`.

But I still get `error: no such module 'Foo'`. Although before I upgraded XCode I got an error `Foo was built with swift 4.2 cannot use in swift 4.1 build` so it seems it uses it at some point.

Have you had any similar problems? 
Sorry, I am not actually an iOS dev so maybe I am missing something obvious.

**Comment by keith** [comment]
This error is because you're compiling with 4.2, but Foo.framework was built with 4.1. This is unrelated to Bazel. You either need to update Foo.framework or pass --swiftcopt=-swift-version --swiftcopt=4 to Bazel.


--
Keith Smiley

**Comment by keith** [comment]
Also you might need to rename to libFoo.a not just Foo.a. That is what we're doing to be in line with static libraries in general. We didn't try without the lib prefix.


--
Keith Smiley

**Comment by codesuki** [comment]
Thanks! It was the other way around. The lib was built with 4.2 and I had 4.1. I upgraded to 4.2 and the error went away, but then I got the error I posted above (`error: no such module 'Foo'`)

I'll try to rename to libFoo :) 

BTW before upgrading xcode the bazel command output showed me that he added the swiftmodule folder with `-I` but the current output with the error doesn't have the `-I`. Probably a different step. I'll post it here in a bit.

**Comment by codesuki** [comment]
After all I was a dummy, checking with `file` I found that my libraries are in fact dynamically linked ones :)
Therefore `objc_framework` together with `module_name` did the trick.
Thanks for your help!

**Comment by keith** [comment]
These are now supported by rules_apple with [`apple_static_framework_import`](https://github.com/bazelbuild/rules_apple/blob/master/doc/rules-general.md#apple_static_framework_import)

We're using that instead now

**Comment by acecilia** [comment]
@allevato I am experiencing a problem related to the `-F` flag that you mentioned.

In a `BUILD` file under a `Carthage` directory I have the following:
```
    apple_dynamic_framework_import(
        name ="AFNetworking",
        framework_imports = native.glob(["Build/iOS/AFNetworking.framework/**",]),
        visibility = ["//visibility:public"],
    )
```
Then, I have a `swift_library` that has `//Carthage:AFNetworking` as a dependency.

When I do `bazel build` I get the following error: 
```
ERROR: /Users/andres/Git/BazelSample/Libraries/SwiftWithPrebuiltObjectiveCAndTests/BUILD.bazel:3:1: Linking Libraries/SwiftWithPrebuiltObjectiveCAndTests/SwiftWithPrebuiltObjectiveCAndTestsTargetTests failed (Exit 1) worker failed: error executing command bazel-out/host/bin/external/build_bazel_rules_swift/tools/worker/worker clang ... (remaining 18 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
ld: warning: directory not found for option '-FCarthage/Build/iOS'
ld: framework not found AFNetworking
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Is there any way to fix this? If not, any workaround?

Thanks!
