### ISSUE TITLE
Swiftmodule-only builds

### ISSUE THREAD

**Issue by kastiglione** [bazelbuild/rules_swift#367]
We have a use case for doing a build that produces only `.swiftmodule`s, without taking the time to build the objects and archives.

Would this be something worth adding to rules_swift?

If not, it would be great to write a rule using the `swift_common` API, specifically something like the  [`compile`](https://github.com/bazelbuild/rules_swift/blob/master/doc/api.md#swift_commoncompile) function, but without emitting objects. Some options to support this from `swift_common`:

1. Add a new function that is much like `compile`, but produces `.swiftmodules` (and perhaps generated headers?)
2. Add switch flags to `compile` to allow callers to opt out of producing object files

I'm not sure what the new function would be called, some ideas are `precompile` or `{generate,emit}_interfaces`.

This potential change also ties in with the idea of pipelined compiles: producing `.swiftmodule`s in a one action, and object files in another.

For context, we use SwiftLint a lot and it uses SourceKit. The SourceKit communication API passes command line flags to SourceKit, and those flags include search module paths. Before using SwiftLint, we do a build but only need the `.swiftmodule`s, not the objects/archives/binaries.

**Comment by kastiglione** [comment]
Relates to https://github.com/bazelbuild/rules_swift/issues/241

**Comment by thomasvl** [comment]
Quick thought - isn't this where output groups could come in handy?  i.e. - no special flags needed, just tell bazel you only care about a specific output group (instead of the default), and as long as the rules vend logical groups to get sub items, you get the behavior generally?  (and other targets can even pick up those outputs via [`filegroup`](https://docs.bazel.build/versions/master/be/general.html#filegroup.output_group) as inputs rather than the defaults.

**Comment by kastiglione** [comment]
Can rules inspect the `--output_groups` values? If so then yes it would be great if we could build with `--output_groups=-object_files`, and then have rules_swift generate actions that have `-emit-module` but not `-emit-object`.

**Comment by allevato** [comment]
There are some changes planned in the (near, I hope) future that should help out here.

I've discussed this a bit before, but I do plan to split the compile action into separate module-compile and object-compile actions as part of the work that moves to using precompiled modules for C/Objective-C dependencies. Doing it before that would end up harming performance if you have deep or complex C/Obj-C dependency graphs, because instead of having one ClangImporter instance per Swift module doing all the work of parsing those headers, you'd have two doing the same work. (Assume the implicit module cache isn't being used, which would be the case for two actions running in parallel on different remote machines anyway.) But if we explicitly precompile the modules, we avoid that.

Once that's done, no API changes should be necessary—the `.swiftmodule` files would be the outputs of the module-compiling actions, and you could write a custom rule that grabs a `SwiftInfo` provider's `swiftmodules` (along with headers and whatever else you need) and passes them to SwiftLint/SourceKit/etc. Bazel would still register all the object-compiling actions and static-archiving from `swift_library` targets, which is totally fine—if you never use any of those outputs as inputs to other actions, the actions will get pruned and never executed. That's the behavior you want, because it doesn't require you to change anything else about your build. You just write a custom rule that says "these are the only outputs I care about" and Bazel can figure the rest out.

Having a new `swift_common` API and writing a custom rule using that is what you **don't** want to do, because you'd have to replicate your entire `swift_library` target graph using that new rule, just to change the outputs of the compiler.

**Comment by keith** [comment]
I think with https://github.com/bazelbuild/rules_swift/issues/241 + output groups you can mostly get what you'd want here
