### ISSUE TITLE
Support -incremental mode

### ISSUE THREAD

**Issue by allevato** [bazelbuild/rules_swift#48]
We may be able to do this with a Bazel persistent worker, which would let us non-hermetically collect the outputs of a library's previous compilations and feed them back in as inputs to future compilations, so that the driver can detect whether they have changed.

However, this is more complicated than simply flipping on a flag—we'll need to design and build a local server that is used as the worker process.

**Comment by keith** [comment]
Are there any related issues elsewhere about supporting the Swift-style incremental compilation model? It sounds like kotlin and rust might also benefit from support for this in bazel, although I'm not 100% sure they use exactly the same model.

**Comment by pauldraper** [comment]
bazel-discuss [using a stateful compiler with Bazel](https://groups.google.com/forum/#!topic/bazel-discuss/3iUy5jxS3S0)

rules_scala [Should we re-consider zinc's incremental compilation?](https://github.com/bazelbuild/rules_scala/issues/328)

I helped author https://github.com/andyscott/rules_scala_annex implements Zinc (stateful incremental Scala compiler). There, the stateful incrementality an opt-in for workers.

**Comment by kastiglione** [comment]
Thanks for the references @pauldraper.

**Comment by keith** [comment]
Posted the first blocker we hit while working on the persistent worker approach here https://github.com/bazelbuild/bazel/issues/6223

**Comment by kastiglione** [comment]
In https://github.com/bazelbuild/rules_apple/issues/21#issuecomment-294537896, @​dmishe listed two approaches: a non-sandbox approach (persisting incremental build artifacts in the file system), and a persistent worker approach. What are the trade-offs between the two alternative options?

**Comment by keith** [comment]
Posted another blocker we hit https://github.com/bazelbuild/bazel/issues/6230 in theory we could work around this by using a list for building the linker arguments, but being able to combine Args objects seems reasonable to solve this as well.

**Comment by pauldraper** [comment]
> In bazelbuild/rules_apple#21 (comment), @​dmishe listed two approaches: a non-sandbox approach (persisting incremental artifacts in the file system), and a persistent worker approach. What are the trade-offs between the two alternative options?

Both cases are fairly similar to implement, as I imagine(?) the worker will still persist files on disk. The ergonomics of selecting incremental compilation can differ.

Note you will still want to make sure a non-worker, sandboxed, non-incremental fully deterministic method exists.

---

For reference, this is how https://github.com/andyscott/rules_scala_annex works:

If the compiler worker receives a `--persistent_dir=<path>` startup flag, then it uses that path to stash and retrieve previous state. (This path is resolved relative to the execution root; currently it is not supported with worker sandboxing.)

My usage:

* There is a distributed cache
* Devs use `--worker_extra_flag=ScalaCompile=--persistent_dir=<path>` and read from a distributed cache.
* CI does not use `--persistent_dir`. It reads and writes to the distributed cache.

Devs get fast builds. CI gets assuredly deterministic builds (plus, the "previous build" is not always anyway). Devs can use CI's cache because `--worker_extra_flag` is not part of the cache key.

Philosophically, I view stateful compilation as a worker-ish thing. The purpose of workers is to reuse expensive state from one action to the next -- typically JIT. Stateful compilation is simply additional state that the worker reuses.

**Comment by keith** [comment]
@pauldraper thanks for all the context here. I noticed that you're using a hidden directory inside the execution root? Is this required? It looks like in my testing it is, and if it isn't hidden bazel wipes it out between builds, is that your understanding as well?

**Comment by pauldraper** [comment]
I believe it can be any name, so long as it doesn't conflict with existing paths (packages). There wasn't a strong reason to make it hidden.
