### ISSUE TITLE
Running swift_test on macOS

### ISSUE THREAD

**Issue by keith** [bazelbuild/rules_swift#51]
Currently if you try to run the `swift_test` example on macOS like this:

```
bazel test //examples/xplatform/xctest:xctest
```

You get this error:

```
ERROR: /Users/ksmiley/dev/rules_swift/examples/xplatform/xctest/BUILD:5:1: SwiftLinkExecutable examples/xplatform/xctest/xctest failed (Exit 1)
ld: warning: directory not found for option '-L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift_static/iphonesimulator'
ld: warning: Auto-Linking library not found for -lswiftMetal
ld: warning: Auto-Linking library not found for -lswiftCoreImage
ld: warning: Auto-Linking library not found for -lswiftDispatch
...
many missing symbols errors
```

This is because bazel is defaulting to the iPhoneSimulator platform instead of macOS. It seems like this is because the platform_type is never being propagated since we don't have a platform specific rule here.

You can work around this using this undocumented option: https://github.com/bazelbuild/bazel/blob/b853e930228e4e8039c8df2bfac1e55de00230b0/src/main/java/com/google/devtools/build/lib/rules/apple/AppleCommandLineOptions.java#L194-L204 like this:

```
bazel test //examples/xplatform/xctest:xctest --apple_platform_type macos
```

When you run this it appears everything works correctly:

```
INFO: Build options have changed, discarding analysis cache.
INFO: Analysed target //examples/xplatform/xctest:xctest (0 packages loaded).
INFO: Found 1 test target...
Target //examples/xplatform/xctest:xctest up-to-date:
  bazel-bin/examples/xplatform/xctest/xctest
INFO: Elapsed time: 2.561s, Critical Path: 2.27s
INFO: 3 processes: 3 darwin-sandbox.
INFO: Build completed successfully, 4 total actions
//examples/xplatform/xctest:xctest                                       PASSED in 0.2s

Executed 1 out of 1 test: 1 test passes.
INFO: Build completed successfully, 4 total actions
```

But upon further investigation:

```
% cat bazel-out/darwin-fastbuild/testlogs/examples/xplatform/xctest/xctest/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="examples/xplatform/xctest/xctest" tests="1" failures="0" errors="0">
    <testcase name="examples/xplatform/xctest/xctest" status="run" duration="0" time="0"></testcase>
    <system-out><![CDATA[]]></system-out>
  </testsuite>
</testsuites>
```

You can see that no tests are actually being run. You can verify this by changing this line https://github.com/bazelbuild/rules_swift/blob/6988c4466febea958edc90c448b4bba7feb3a636/examples/xplatform/xctest/SimpleTests.swift#L25 to `XCTAssertEqual(value, 3)`, and you'll see the tests still pass.

I assume this rule is supposed to work on macOS as well as Linux for swift tests, so it looks like the test discovery part of this needs updating.

**Comment by allevato** [comment]
#32 just covers the test runner issue, not the platform issue.

I thought I had documented the platform issue, but apparently not. Unlike the Apple rules, `swift_binary` does not do any platform transitions; it merely builds for the target CPU/platform that you specify, or if you don't specify one, it uses the default. For historical reasons, the default platform for actions that link with the Apple CROSSTOOL is iOS. ☹️ 

There are no plans to have `swift_binary` specify a platform type, because they're meant to be platform-agnostic; if you need that kind of control, then use one of the rules_apple platform-specific rules instead (e.g., `macos_unit_test`). However, this is still very much worth fixing in the future because someone *should* be able to write a `swift_test` target that just runs correctly on either Linux or macOS, whichever the Bazel host platfrom may be.

To be extra safe, I prefer specifying both the CPU and platform type explicitly:

```
bazel test //foo:foo_tests --cpu=darwin_x86_64 --apple_platform_type=macos
```

Of course, that still won't work because of #32. 🙂   For now, use `macos_unit_test`.

(The same issue holds for `swift_binary` as well, but `swift_binary` has other uses that work well today—you can have a `swift_binary` be built as a tool dependency of another rule, and since tool dependencies are built in the host configuration, they *will* be built for macOS and then execute correctly in later build actions.)

**Comment by kastiglione** [comment]
Should `apple_platform_type` be changed away from `UNDOCUMENTED`?

**Comment by allevato** [comment]
No, the legacy behavior of Bazel using iOS as the default target on macOS should be changed so that the flag is not required and we match Bazel's behavior on Linux (where, if you don't specify, the default target platform is the same as the host platform).

**Comment by kastiglione** [comment]
And if you want to cross compile, do you not need `apple_platform_type` then?

**Comment by allevato** [comment]
Ideally, that would be handled automatically by CROSSTOOL when it selects the toolchain based whether you pass `--cpu=darwin_x86_64`, `--cpu=ios_x86_64`, or something else. IIRC, the `--apple_platform_type` flag is redundant but needed for some of those legacy use cases, and there's still a lot of cleanup to do.

The long-term goal, of course, is to [redesign build configuration](https://docs.google.com/document/d/1vc8v-kXjvgZOdQdnxPTaV0rrLxtP2XwnD2tAZlYJOqw/edit?usp=sharing) so that `bazel build //target` just works without _any_ flags.

**Comment by kastiglione** [comment]
Thanks for the explanation 🍻

**Comment by allevato** [comment]
Since #32 fixed the test runner issue and the platform issue is handled by passing Bazel flags, I'm going to go ahead and close this out.

**Comment by keith** [comment]
I've submitted a PR to bazel to change this default https://github.com/bazelbuild/bazel/pull/6366 we'll see what the response is like
