### ISSUE TITLE
Investigate using json for worker

### ISSUE THREAD

**Issue by keith** [bazelbuild/rules_swift#516]
This is supported now and would reduce our usage of proto which can take a while to build on its own. We already have a json parsing library in the worker for output file map manipulation 

https://github.com/bazelbuild/bazel/issues/7998#issuecomment-721796702

**Comment by arturdryomov** [comment]
@keith, do you have ideas about how stable the JSON support gonna be? It would be nice to know or have some insight about whether it will be removed from Bazel itself. I would like to switch from PB to JSON in Detekt rules but not sure if it’s a good idea to require setting a Bazel execution flag (`--experimental_worker_allow_json_protocol`) from clients. TBH it’s tempting since compiling PB from scratch is a bit ridiculous.

**Comment by keith** [comment]
It was just added so I'm optimistic it will stick around

**Comment by arturdryomov** [comment]
@keith, did some digging in buildfoundation/bazel_rules_detekt#107.

**Comment by keith** [comment]
Thanks for the link
