### ISSUE TITLE
File paths with spaces aren't handled by params files

### ISSUE THREAD

**Issue by keith** [bazelbuild/rules_swift#60]
After [this commit](https://github.com/bazelbuild/rules_swift/commit/c67072a07f05929b613ae488fe29fb0a69f3646d#diff-9cbe8d63c6561748aa94fe743f6178b2R472) to use params files for swiftc, our builds started failing since we have source files with spaces in the name.

The core issue here is unrelated to bazel (and filed [here](https://bugs.swift.org/browse/SR-8828)) assuming that this should be supported, but otherwise (and in the meantime) we might want to fix this in bazel to quote or escape the file paths in this file.

**Comment by keith** [comment]
Actually it looks like clang doesn't support this either, so I assume this was intentional on the Swift side and we should fix it here

**Comment by allevato** [comment]
I commented on the Swift bug you linked. The standalone example is working as expected, because there aren't quotes around the filename.

For Swift builds specifically, if you can grab one of the params files that Bazel creates and show that a path with a space in it isn't being quoted, that would be good to know. If that's the case, it's not a rules_swift bug, but a Bazel bug. We just use the `Args` API to add files to the argument list, and it's up to that object to quote/escape things correctly (if spaces in filenames are even meant to be supported; I tend to avoid them because they always cause problems).

**Comment by keith** [comment]
> For Swift builds specifically, if you can grab one of the params files that Bazel creates and show that a path with a space in it isn't being quoted, that would be good to know.

Yes this is the case now.

> if spaces in filenames are even meant to be supported; I tend to avoid them because they always cause problems

I agree but it still seems like something we should fix here.

But it sounds like I should move this issue to bazel?

**Comment by allevato** [comment]
> But it sounds like I should move this issue to bazel?

Yes, please do. If the intent is for params files generated by `Args` to support spaces in paths, then it will need to be fixed there.

**Comment by keith** [comment]
Filed here https://github.com/bazelbuild/bazel/issues/6224

**Comment by kastiglione** [comment]
@allevato why `compile_args.set_param_file_format("multiline")`? The default param file format (`"shell"`) would solve this problem, would it break other things?

**Comment by keith** [comment]
Based on the documentation here https://docs.bazel.build/versions/master/skylark/lib/Args.html#set_param_file_format it seems like that might be the intention. I've submitted a PR here assuming that this is a fix we should do here https://github.com/bazelbuild/rules_swift/pull/61

**Comment by allevato** [comment]
#61 by itself will break us internally. There are a couple places I know of where I "cheat" to pass space-separated string arguments on a single line, and that change will quote them incorrectly.

However, that cheat should be unnecessary now because of some other improvements to the `Args` APIs, so I'll make the necessary changes internally tomorrow and run it against our CI.
